apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
    - port: 22
      name: ssh
  type: LoadBalancer
