apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
spec:
  selector:
    app: phpmyadmin
  ports:
    - port: 5000
  type: LoadBalancer
