apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
spec:
  selector:
    app: wordpress
  ports:
    - port: 5050
  type: LoadBalancer
